#data source properties
spring:
  datasource:
    data-source-class-name: org.h2.jdbcx.JdbcDataSource
    schema: classpath:/sql/schema.sql
    data: classpath:/sql/data.sql

# JPA properties
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

server:
  port: 9007
  
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true   
    sensitive: false
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000      
---

spring:
  profiles: development
    
#data source properties

  datasource:
    data-source-class-name: org.h2.jdbcx.JdbcDataSource
    schema: classpath:/sql/schema.sql
    data: classpath:/sql/data.sql

# JPA properties
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

server:
  port: 8007
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true   
    sensitive: false
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
