configuration:  
  projectName: config-client-dev
server:
  port: 8005
message:
  greeting: hello from the configuration!
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    hostname: config-client
  client:
    register-with-eureka: true
    
spring:
  application:
    name: xyz
    
