configuration:  
  projectName: config-client-master
server:
  port: 8008
message:
  greeting: hello from the configuration!
 
eureka:
  instance:
    hostname: config-client-override
spring:
  application:
    name: xyz
