server:
  port: 8888

eureka:
  instance:
    hostname: config-server-prod
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CodeBlossoms/cloud-config-repo
    
---
spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          default-label: dev
          uri: https://github.com/CodeBlossoms/cloud-config-repo
  
server:
  port: 7777

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: config-server-dev
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      
---
spring:
  profiles: cloud
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/CodeBlossoms/cloud-config-repo
  
server:
  port: 9999

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: ${vcap.application.uris[0]}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-server.credentials.url}
      
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true   
    sensitive: false
