configuration:  
  projectName: config-client-dev
server:
  port: 8005
message:
  greeting: hello from the configuration!
  
eureka:
  instance:
    hostname: gateway
  client:
    register-with-eureka: true
    fetch-registry: true
