server:
  port: 8888

eureka:
  instance:
    hostname: config-server-prod
    #prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/CodeBlossoms/cloud-config-repo

---
spring:
  profiles: development
  cloud:
    config:
      label: dev
      server:
        git:
          uri: https://github.com/CodeBlossoms/cloud-config-repo
  
server:
  port: 7777

eureka:
  instance:
    hostname: config-server-dev
    #prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
